export const ROLE_LABELS: Record<string, string> = {
  cover: "封面",
  agenda: "目录",
  background: "背景",
  problem: "问题",
  method: "方法",
  architecture: "架构",
  evidence: "证据",
  data: "数据",
  comparison: "对比",
  insight: "洞察",
  conclusion: "结论",
  questions: "问答",
};

export const VARIANT_LABELS: Record<string, string> = {
  "evidence-brief": "判断与证据",
  "content-list": "完整内容",
  hero: "主视觉封面",
  "editorial-cover": "编辑封面",
  "minimal-cover": "极简封面",
  "numbered-list": "编号目录",
  "section-map": "章节地图",
  "agenda-cards": "目录卡片",
  "big-statement": "核心主张",
  "context-cards": "背景要点",
  timeline: "时间线",
  "problem-cards": "问题聚焦",
  contrast: "对照表达",
  "before-after": "前后对比",
  workflow: "工作流",
  "three-stage": "三阶段",
  process: "过程链路",
  "layered-architecture": "分层架构",
  pipeline: "管线架构",
  "hub-spoke": "中心辐射",
  "chart-focus": "图表聚焦",
  "metric-wall": "指标总览",
  "table-highlight": "表格强调",
  "comparison-bars": "对比条形",
  "two-column": "双栏对照",
  scorecard: "评分卡",
  takeaways: "结论要点",
  "summary-grid": "总结网格",
  "next-steps": "下一步",
  "minimal-qa": "极简问答",
  "closing-statement": "收束主张",
  contact: "联系页",
};
